- Gemfile.lock
- app/models/anime.rb
- app/models/figure.rb
- app/models/order.rb
- app/models/review.rb
- app/models/user.rb
- app/views/pages/home.html.erb
- db/migrate/20240713060329_add_attributes_to_users.rb
- db/migrate/20240713060628_create_animes.rb
- db/migrate/20240713060922_create_figures.rb
- db/migrate/20240713061600_create_orders.rb
- db/migrate/20240713062529_create_reviews.rb
- db/schema.rb
- test/models/anime_test.rb
- test/models/figure_test.rb
- test/models/order_test.rb
- test/models/review_test.rb
generate user order figgure review anime
> Generate base models

- .gitignore
- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/models/figure.rb
- app/models/user.rb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/shared/_navbar.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/storage.yml
- db/migrate/20240713070742_create_active_storage_tables.active_storage.rb
- db/schema.rb
cloudinary setup and cl image tag for user avatar
> Cloudinary setup

- app/controllers/figures_controller.rb
- config/routes.rb
- test/controllers/figures_controller_test.rb
> routes setup

- app/controllers/figures_controller.rb
- app/views/figures/index.html.erb
- config/routes.rb
added index route to list all figures in homepage and index.view page since root home was set to root to: figures#index
Preview will show screenshot --->>>
> All figures homepage

- Gemfile.lock
- app/models/anime.rb
- app/models/figure.rb
- app/models/order.rb
- app/models/review.rb
- app/models/user.rb
I did some validations, and want to try pulling, pls let me know if there is anything wrong
> Validation enums

- app/controllers/figures_controller.rb
- app/controllers/purchases/figures_controller.rb
- app/views/purchases/figures/index.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- test/controllers/purchases/figures_controller_test.rb
Created the user story for "buyer can view all purchase history"  new route, controller and view formed.
Also set top left logo button to go to figures#index as root homepage.
> Buyer purchases history view

- app/controllers/application_controller.rb
- app/controllers/figures_controller.rb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/figures/new.html.erb
generated simple form for adding anime figures for sale
added address and username fields, to devise/registrations new and edit
> Seller can list new figures

- app/controllers/orders_controller.rb
- app/views/orders/_order_card.html.erb
- app/views/orders/index.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- test/controllers/orders_controller_test.rb
you can click on the navbar to go to "my dashboard" to see the seller's orders with a menu panel on the left to select other options not yet built.
> Seller dashboard list orders

- app/controllers/figures_controller.rb
- app/views/figures/index.html.erb
fix figure params and added image tag for testing
> fix figure params

- db/seeds.rb
the remain seed makes orders based on the information already there.
> Seed orders

- app/controllers/orders_controller.rb
- app/models/figure.rb
- app/views/figures/new.html.erb
- app/views/orders/new.html.erb
- db/migrate/20240718021826_change_status_from_orders.rb
- db/schema.rb
options change based on the availability of delivery
i spent hours trying to make error show when user is not selecting a mode of delivery, couldn't do it
our seeds right now both have pick up and delivery set to false
> Create new order

- app/controllers/figures_controller.rb
- app/models/figure.rb
- app/views/figures/new.html.erb
- db/migrate/20240718071920_add_pick_up_location_to_figures.rb
- db/schema.rb
- db/seeds.rb
> Figures update

- app/controllers/orders_controller.rb
- app/controllers/reviews_controller.rb
- app/models/order.rb
- app/models/review.rb
- app/views/figures/index.html.erb
- app/views/orders/new.html.erb
- app/views/reviews/new.html.erb
- config/routes.rb
- test/controllers/reviews_controller_test.rb
> Add review

- app/controllers/users_controller.rb
- app/views/users/show.html.erb
- test/controllers/users_controller_test.rb
Added users controller and users, show
> added userviews and users controller

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/card.scss
- app/views/figures/_anime-category-cards.erb
- app/views/figures/index.html.erb
> anime cards

- app/controllers/orders_controller.rb
- app/models/order.rb
- app/views/listed/figures/_order_list.html.erb
- app/views/orders/new.html.erb
- config/routes.rb
> seller can update order status

- app/javascript/controllers/toggle_controller.js
- app/views/listed/figures/index.html.erb
- app/views/shared/_navbar.html.erb
> Dashboard front end

- app/assets/stylesheets/components/_navbar.scss
- app/views/figures/new.html.erb
logo resize, new figure form bootstrap and button verbage
> logo resize, new figure form bootstrap and button verbage

- app/assets/stylesheets/pages/_banner.scss
- app/views/figures/index.html.erb
> front page cards

- app/controllers/figures_controller.rb
- app/views/figures/_form.html.erb
- app/views/figures/edit.html.erb
- app/views/listed/figures/_product_list.html.erb
- config/routes.rb
> Seller can edit figure

- app/assets/stylesheets/components/_dashboard.scss
- app/controllers/figures_controller.rb
- app/views/figures/_form.html.erb
- app/views/figures/edit.html.erb
- app/views/listed/figures/_product_list.html.erb
- app/views/listed/figures/_review_list.html.erb
- app/views/listed/figures/index.html.erb
- config/routes.rb
- db/seeds.rb
> Dashboard reviews

- app/assets/stylesheets/components/_searchbar_homepage.scss
> fixed search bar scss

- app/views/shared/_figure_card.html.erb
Collapse cards now do it individually
> fix for collapse card

- app/assets/stylesheets/components/_dashboard.scss
- app/assets/stylesheets/components/_figure_card.scss
- app/javascript/controllers/toggle_controller.js
- app/views/listed/figures/_order_list.html.erb
- app/views/shared/_figure_card.html.erb
> Figure cards chevron

- app/assets/stylesheets/components/_dashboard.scss
- app/javascript/controllers/toggle_controller.js
- app/views/listed/figures/_order_list.html.erb
order cards have chevron at the end of it
> Collapse order cards

- app/controllers/figures_controller.rb
- app/controllers/listed/figures_controller.rb
- app/views/figures/_banner.html.erb
> Call to action

- app/assets/stylesheets/components/_dashboard.scss
- app/views/listed/figures/index.html.erb
- app/views/purchased/figures/index.html.erb
> add seller and buyer buttons

- app/assets/stylesheets/components/_dashboard.scss
- app/views/listed/figures/index.html.erb
- app/views/purchased/figures/index.html.erb
added spacing in seller/buyer dashboard list
> Fix dashboard div
